### ISSUE TITLE
Feature request: NVIDIA CUDA plugin for XMRig miner

### ISSUE THREAD

**Issue by flolu** [hinto-janaiyo/monero-bash#4]
This is just a suggestion. I'm not sure how complicated it would be to implement. But I would love to see [xmrig-cuda](https://github.com/xmrig/xmrig-cuda) plugin being added to `monero-bash`.

**Comment by hinto-janai** [comment]
Monero (RandomX) mining is very inefficient with GPUs. It's much better to mine a different coin with them.

Sorry for the late reply.
